site_name: "CHEMROF"
theme:
  name: material
  analytics:
    gtag: G-2SYBSJVZ23
  palette:
    scheme: default
    primary: purple
  features:
    - content.tabs.link
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Introduction: home.md
  - Database: database.md
  - Ontology: ontology.md
  - Schema: index.md
  - Metaclasses: metaclasses.md
  - Credits: credits.md
site_url: https://chemkg.github.io/chemrof/
repo_url: https://github.com/chemkg/chemrof/
