site_name: "Chemical Entities Mixtures Reactions Ontological Framework"
theme:
  name: readthedocs
  analytics:
    gtag: G-2SYBSJVZ23
nav:
  - Introduction: home.md
  - Database: database.md
  - Ontology: ontology.md
  - Schema: index.md
  - Metaclasses: metaclasses.md
  - Credits: credits.md
site_url: https://chemkg.github.io/chemrof/
repo_url: https://github.com/chemkg/chemrof/
