site_name: "CHEMROF"
theme:
  name: material
  analytics:
    gtag: G-2SYBSJVZ23
  palette:
    scheme: default
    primary: purple
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2:
      version: 9.3.0
nav:
  - Introduction: home.md
  - Database: database.md
  - Ontology: ontology.md
  - Schema: index.md
  - Metaclasses: metaclasses.md
  - Credits: credits.md
site_url: https://chemkg.github.io/chemrof/
repo_url: https://github.com/chemkg/chemrof/
