site_name: "chem schema"
theme:
  name: readthedocs
  analytics:
    gtag: G-2SYBSJVZ23
nav:
  - Introduction: home.md
  - Database: database.md
  - Ontology: ontology.md
  - Schema: index.md
  - Metaclasses: metaclasses.md
  - Credits: credits.md
